name: teacher_pro
description: Professional Teacher Tool
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  vector_math: ^2.1.4

flutter:
  uses-material-design: true
  
